name: 04 - Using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 01-using-actions/react-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm run test